import { RestApi } from '@servicenow/sdk/core';

RestApi({
  $id: Now.ID['sc-widget'],
  name: 'Script Console Widget API',
  serviceId: 'console_widget',
  consumes: 'application/json',
  routes: [
    {
      $id: Now.ID['sc-widget-get-widget'],
      name: 'Get Widget',
      method: 'GET',
      script: Now.include('./get-widget.server.js'),
      consumes: 'application/json',
      produces: 'application/json,application/xml,text/xml',
      path: '/get_widget/{id}',
    },
    {
      $id: Now.ID['sc-widget-get-widgets'],
      method: 'GET',
      name: 'Get Recent Widgets',
      consumes: 'application/json',
      script: Now.include('./get-widgets.server.js'),
      produces: 'application/json,application/xml,text/xml',
      path: '/recent_widgets',
    },
    {
      $id: Now.ID['sc-widget-get-dependencies'],
      method: 'GET',
      name: 'Get Widget Dependencies',
      consumes: 'application/json',
      script: Now.include('./get-widget-deps.server.js'),
      produces: 'application/json,application/xml,text/xml',
      path: '/get_dependencies/{table}/{widget}/{field}',
    },
    {
      $id: Now.ID['sc-widget-refresh-dep-counts'],
      method: 'GET',
      name: 'Refresh Widget Dependency Counts',
      consumes: 'application/json',
      script: Now.include('./refresh-counts.server.js'),
      produces: 'application/json,application/xml,text/xml',
      path: '/refresh_dep_count/{widget}',
    },
    {
      $id: Now.ID['sc-widget-create-dependency'],
      method: 'POST',
      name: 'Create Widget Dependency',
      consumes: 'application/json',
      script: Now.include('./create-widget-dep.server.js'),
      produces: 'application/json,application/xml,text/xml',
      path: '/create_dependency',
    },
    {
      $id: Now.ID['sc-widget-clone-widget'],
      method: 'POST',
      name: 'Clone Widget',
      consumes: 'application/json',
      script: Now.include('./clone-widget.server.js'),
      produces: 'application/json,application/xml,text/xml',
      path: '/clone_widget/{widget}',
    },
    {
      $id: Now.ID['sc-widget-create-macro'],
      method: 'POST',
      name: 'Create Macro',
      consumes: 'application/json',
      script: Now.include('./create-macro.server.js'),
      produces: 'application/json,application/xml,text/xml',
      path: '/create_macro',
    },
  ],
});
