import { RestApi } from '@servicenow/sdk/core';

RestApi({
  $id: Now.ID['sc-core'],
  name: 'Script Console Core API',
  serviceId: 'console_core',
  consumes: 'application/json',
  routes: [
    {
      $id: Now.ID['sc-core-get-app-config'],
      name: 'Get App Config',
      method: 'GET',
      script: Now.include('./app-config.server.js'),
      consumes: 'application/json',
      produces: 'application/json,application/xml,text/xml',
      path: '/app_config',
    },
    {
      $id: Now.ID['sc-core-get-table-data'],
      name: 'Get Table Data',
      method: 'GET',
      script: Now.include('./table-data.server.js'),
      consumes: 'application/json',
      produces: 'application/json,application/xml,text/xml',
      path: '/table_data/{table}',
    },
    {
      $id: Now.ID['sc-core-get-stats-data'],
      name: 'Get Stats Data',
      method: 'GET',
      script: Now.include('./stats-data.server.js'),
      consumes: 'application/json',
      produces: 'application/json,application/xml,text/xml',
      path: '/stats_data',
    },
    {
      $id: Now.ID['sc-core-ref-display'],
      name: 'Get Reference Display',
      method: 'GET',
      script: Now.include('./ref-display.server.js'),
      consumes: 'application/json',
      produces: 'application/json,application/xml,text/xml',
      path: '/ref_display/{table}',
    },
    {
      $id: Now.ID['sc-core-form-data'],
      name: 'Get Form Data',
      method: 'GET',
      script: Now.include('./form-data.server.js'),
      consumes: 'application/json',
      produces: 'application/json,application/xml,text/xml',
      path: '/form_data/{table}/{id}',
    },
    {
      $id: Now.ID['sc-core-script-data'],
      name: 'Get Script Data',
      method: 'GET',
      script: Now.include('./script-data.server.js'),
      consumes: 'application/json',
      produces: 'application/json,application/xml,text/xml',
      path: '/script_data/{table}/{id}/{field}',
    },
    {
      $id: Now.ID['sc-core-global-method'],
      method: 'POST',
      name: 'Global Method',
      consumes: 'application/json',
      script: Now.include('./global-method.server.js'),
      produces: 'application/json,application/xml,text/xml',
      path: '/global_method/{name}',
    },
  ],
});
